// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs4VZa_FkmD1Jfbhc9AcF7jmLN_kd3KsU',
    appId: '1:147660500949:web:521fdfae10240b5cef175c',
    messagingSenderId: '147660500949',
    projectId: 'iharu-ae2e9',
    authDomain: 'iharu-ae2e9.firebaseapp.com',
    storageBucket: 'iharu-ae2e9.firebasestorage.app',
    measurementId: 'G-1RRPP8XJ63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjdsC-8JFUWDbrQBN6yOwgp5WdqvznaG0',
    appId: '1:147660500949:android:f24dcc2b814e2f6def175c',
    messagingSenderId: '147660500949',
    projectId: 'iharu-ae2e9',
    storageBucket: 'iharu-ae2e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8BDOihWegIM6FUsPG7Qa3hWn0Req5ONU',
    appId: '1:147660500949:ios:1e4fcfca1275b865ef175c',
    messagingSenderId: '147660500949',
    projectId: 'iharu-ae2e9',
    storageBucket: 'iharu-ae2e9.firebasestorage.app',
    iosBundleId: 'com.example.aiharuFlutterAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8BDOihWegIM6FUsPG7Qa3hWn0Req5ONU',
    appId: '1:147660500949:ios:1e4fcfca1275b865ef175c',
    messagingSenderId: '147660500949',
    projectId: 'iharu-ae2e9',
    storageBucket: 'iharu-ae2e9.firebasestorage.app',
    iosBundleId: 'com.example.aiharuFlutterAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs4VZa_FkmD1Jfbhc9AcF7jmLN_kd3KsU',
    appId: '1:147660500949:web:49dc2f9de381d97eef175c',
    messagingSenderId: '147660500949',
    projectId: 'iharu-ae2e9',
    authDomain: 'iharu-ae2e9.firebaseapp.com',
    storageBucket: 'iharu-ae2e9.firebasestorage.app',
    measurementId: 'G-2ST7CXZCQV',
  );
}
